name: barrim
description: "Discover the best of your neighborhood with Barrim."
publish_to: 'none'

version: 1.0.9+6

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # GCP OAuth dependencies (no Firebase needed)
  # firebase_core: ^3.14.0  # Removed - using GCP OAuth instead
  # firebase_messaging: ^15.2.7  # Removed - using GCP OAuth instead
  
  # Other dependencies
  flutter_launcher_icons: ^0.14.4
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  # flutter_native_splash: ^2.4.5  # Removed splash screen
  google_maps_flutter: ^2.10.1
  location: ^5.0.3
  csc_picker: ^0.2.7
  image_picker: ^1.1.2
  http: ^1.3.0
  shared_preferences: ^2.5.2
  google_sign_in: ^6.3.0
  provider: ^6.1.2
  geolocator: ^10.0.0
  geocoding: ^3.0.0
  flutter_svg: ^2.0.7
  lottie: ^3.3.1
  flutter_map: ^5.0.0
  latlong2: ^0.9.0
  flutter_polyline_points: ^2.1.0
  permission_handler: ^11.0.1
  carousel_slider: ^4.2.1
  path: ^1.8.2
  http_parser: ^4.0.2
  flutter_local_notifications: ^19.1.0
  share_plus: ^10.1.4
  qr_flutter: ^4.1.0
  url_launcher: ^6.3.1
  intl: ^0.20.2
  flutter_secure_storage: ^9.2.4
  jwt_decoder: ^2.0.1
  cached_network_image: ^3.4.1
  web_socket_channel: ^2.4.0
  table_calendar: ^3.2.0
  video_player: ^2.9.5
  country_picker: ^2.0.27
  rename: ^3.1.0
  sign_in_with_apple: ^7.0.1
  image: ^4.1.3
  flutter_dotenv: ^5.1.0
  firebase_messaging: ^15.2.7
  firebase_core: ^3.14.0


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo/app_logo.jpg"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/logo/app_logo.jpg"
  windows:
    generate: true
    image_path: "assets/logo/app_logo.jpg"
  macos:
    generate: true
    image_path: "assets/logo/app_logo.jpg"

# Splash screen removed
# flutter_native_splash:
#   color: "#f7f6f1"
#   color_dark: "#272727"
#   image: assets/logo/logo.png
#   image_dark: assets/logo/logo.png
#   android_12:
#     image: assets/logo/logo.png
#     icon_background_color: "#f7f6f1"
#     image_dark: assets/logo/logo.png
#     icon_background_color_dark: "#272727"
#     
#   web: false
#   android: true
#   ios: true
#   # Increase image size
#   android_gravity: center
#   ios_content_mode: center
#   fullscreen: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/images/
    - assets/icons/
    - assets/logo/
    - assets/countries_districts_cities.json
    - .env

  uses-material-design: true