// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCv-XhnrDaOgM-EzK9VMHHbz8gs8yLT8lU',
    appId: '1:307776183600:web:9b6bd80ac294904bb5fcf5',
    messagingSenderId: '307776183600',
    projectId: 'barrim-3b45a',
    authDomain: 'barrim-3b45a.firebaseapp.com',
    storageBucket: 'barrim-3b45a.firebasestorage.app',
    measurementId: 'G-H0ML7PXS6V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDG54P5AZ3i3uj1l_A1SCIi-vutN0nVAK8',
    appId: '1:307776183600:android:1664503f45a706b1b5fcf5',
    messagingSenderId: '307776183600',
    projectId: 'barrim-3b45a',
    storageBucket: 'barrim-3b45a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYwCHkNIoKE2-Dxn4ck3C5N_xxNOCnUxI',
    appId: '1:307776183600:ios:5bf9edb81f519538b5fcf5',
    messagingSenderId: '307776183600',
    projectId: 'barrim-3b45a',
    storageBucket: 'barrim-3b45a.firebasestorage.app',
    androidClientId: '307776183600-p4ra4n80v0tajt573n8q5t4a684c0sn6.apps.googleusercontent.com',
    iosClientId: '307776183600-aoags2ect1p5i6rmebgsltb9ipsfin86.apps.googleusercontent.com',
    iosBundleId: 'com.Dev.DevBarrim',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYwCHkNIoKE2-Dxn4ck3C5N_xxNOCnUxI',
    appId: '1:307776183600:ios:5bf9edb81f519538b5fcf5',
    messagingSenderId: '307776183600',
    projectId: 'barrim-3b45a',
    storageBucket: 'barrim-3b45a.firebasestorage.app',
    androidClientId: '307776183600-p4ra4n80v0tajt573n8q5t4a684c0sn6.apps.googleusercontent.com',
    iosClientId: '307776183600-aoags2ect1p5i6rmebgsltb9ipsfin86.apps.googleusercontent.com',
    iosBundleId: 'com.Dev.DevBarrim',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCv-XhnrDaOgM-EzK9VMHHbz8gs8yLT8lU',
    appId: '1:307776183600:web:09405d1f6c0e2389b5fcf5',
    messagingSenderId: '307776183600',
    projectId: 'barrim-3b45a',
    authDomain: 'barrim-3b45a.firebaseapp.com',
    storageBucket: 'barrim-3b45a.firebasestorage.app',
    measurementId: 'G-PV9ZXF63ED',
  );
}
