// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDG54P5AZ3i3uj1l_A1SCIi-vutN0nVAK8',
    appId: '1:307776183600:web:1664503f45a706b1b5fcf5',
    messagingSenderId: '307776183600',
    projectId: 'barrim-3b45a',
    authDomain: 'barrim-3b45a.firebaseapp.com',
    storageBucket: 'barrim-3b45a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDG54P5AZ3i3uj1l_A1SCIi-vutN0nVAK8',
    appId: '1:307776183600:android:1664503f45a706b1b5fcf5',
    messagingSenderId: '307776183600',
    projectId: 'barrim-3b45a',
    storageBucket: 'barrim-3b45a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDG54P5AZ3i3uj1l_A1SCIi-vutN0nVAK8',
    appId: '1:307776183600:ios:1664503f45a706b1b5fcf5',
    messagingSenderId: '307776183600',
    projectId: 'barrim-3b45a',
    storageBucket: 'barrim-3b45a.firebasestorage.app',
    iosBundleId: 'com.Barrim.AppBarrim',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDG54P5AZ3i3uj1l_A1SCIi-vutN0nVAK8',
    appId: '1:307776183600:ios:1664503f45a706b1b5fcf5',
    messagingSenderId: '307776183600',
    projectId: 'barrim-3b45a',
    storageBucket: 'barrim-3b45a.firebasestorage.app',
    iosBundleId: 'com.Barrim.AppBarrim',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDG54P5AZ3i3uj1l_A1SCIi-vutN0nVAK8',
    appId: '1:307776183600:web:1664503f45a706b1b5fcf5',
    messagingSenderId: '307776183600',
    projectId: 'barrim-3b45a',
    authDomain: 'barrim-3b45a.firebaseapp.com',
    storageBucket: 'barrim-3b45a.firebasestorage.app',
  );
}
